//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreshFruit.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class freshfruitEntities : DbContext
    {
        public freshfruitEntities()
            : base("name=freshfruitEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<fruit_user> fruit_user { get; set; }
        public virtual DbSet<fruit_user_address> fruit_user_address { get; set; }
        public virtual DbSet<fruit_user_log> fruit_user_log { get; set; }
        public virtual DbSet<fruit_user_points> fruit_user_points { get; set; }
    }
}
