//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreshFruit.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class fruit_user
    {
        public int user_id { get; set; }
        public bool user_sex { get; set; }
        public long user_birthday { get; set; }
        public int user_reg_time { get; set; }
        public Nullable<int> user_recommend_uid { get; set; }
        public Nullable<int> user_email_time { get; set; }
        public bool Is_email_validated { get; set; }
        public Nullable<bool> Is_delete { get; set; }
    }
}
