//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreshFruit.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class fruit_user_address
    {
        public int Address_id { get; set; }
        public string Address_name { get; set; }
        public int User_id { get; set; }
        public string Consignee { get; set; }
        public string Email { get; set; }
        public short Country { get; set; }
        public short Province { get; set; }
        public short City { get; set; }
        public short District { get; set; }
        public string Address { get; set; }
        public string Zipcode { get; set; }
        public string Tel { get; set; }
        public string Mobile { get; set; }
        public string Sign_building { get; set; }
        public string Best_time { get; set; }
        public bool IsEncryption { get; set; }
    }
}
